[package]
name = "examples"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "examples"
path = "main.rs"

[dependencies]
kl = { path = "../kel" }
clap = {version = "4.5.30", features = ["derive"]}
serde_json = { version = "1.0.140" }
regex = "1"
